// Do NOT edit; this file is autogenerated.
// #note master 0 has highest priority.
module XBAR_2_1(
	input i_reset,
	input i_clock,

	// Master 0
	input i_m0_rw,
	input i_m0_request,
	output bit o_m0_ready,
	input [31:0] i_m0_address,
	output bit [31:0] o_m0_rdata,
	input [31:0] i_m0_wdata,

	// Master 1
	input i_m1_rw,
	input i_m1_request,
	output bit o_m1_ready,
	input [31:0] i_m1_address,
	output bit [31:0] o_m1_rdata,
	input [31:0] i_m1_wdata,

	// Slave 0
	output bit o_s0_rw,
	output bit o_s0_request,
	input i_s0_ready,
	output bit [31:0] o_s0_address,
	input [31:0] i_s0_rdata,
	output bit [31:0] o_s0_wdata
);
	bit [3:0] s0_source;
	bit [3:0] next_s0_source;

	always_ff @(posedge i_clock) begin
		s0_source <= next_s0_source;
	end

	always_comb begin
		next_s0_source = 4'h0;

		o_s0_rw = 1'b0;
		o_s0_request = 1'b0;
		o_s0_address = 32'h0;
		o_s0_wdata = 32'h0;

		o_m0_ready = 1'b0;
		o_m0_rdata = 32'h0;
		o_m1_ready = 1'b0;
		o_m1_rdata = 32'h0;

		if (i_m1_request) begin
			if (
				i_m1_address[31:28] == 4'h0 &&
				(s0_source == 4'h0 || s0_source == 4'h2)
			) begin
				o_s0_rw = i_m1_rw;
				o_s0_request = 1'b1;
				o_m1_ready = i_s0_ready;
				o_s0_address = { 4'b0, i_m1_address[27:0] };
				o_m1_rdata = i_s0_rdata;
				o_s0_wdata = i_m1_wdata;
				next_s0_source = 4'h2;
			end
		end

		if (i_m0_request) begin
			if (
				i_m0_address[31:28] == 4'h0 &&
				(s0_source == 4'h0 || s0_source == 4'h1)
			) begin
				o_s0_rw = i_m0_rw;
				o_s0_request = 1'b1;
				o_m0_ready = i_s0_ready;
				o_s0_address = { 4'b0, i_m0_address[27:0] };
				o_m0_rdata = i_s0_rdata;
				o_s0_wdata = i_m0_wdata;
				next_s0_source = 4'h1;
			end
		end
	end
endmodule
